---
### provision AWS EC2 instance

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: test-keypair
    instance_type: t2.micro
    security_group: sg-06bded1a985de0760
    image: ami-9887c6e7
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group_id: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         count: 2
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-0043dd849a39a5907
         assign_public_ip: yes
         instance_tags:
          type: test_instance
         volumes:
          - device_name: /dev/sdb
            volume_size: 8
            volume_type: gp2
            delete_on_termination: True
      register: ec2

    # - name: Add new instance to host group
    #   add_host: hostname={{ item.public_ip }} groupname=launched
    #   with_items: ec2.instances

    # - name: Wait for SSH to come up
    #   wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    #   with_items: ec2.instances

    # - name: install Apache
    #   hosts: launched
    #   remote_user: ec2-user
    #   roles:
    #     - apache
        