---
### Playbook to terminate all instances with a given tag

- name: Playbook to terminate all instances with a given tag
  hosts: localhost
  gather_facts: True
  #Vars Passed as CLI argument
  vars:
    region: "{{ region }}" 
    key : "{{ key }}"
    value : "{{ value }}" 
  tasks:
    # Gather facts about any instance with the tag(Key, Value) passed
    - name: Gather EC2 facts
      ec2_instance_facts :
        filters:
          "{{ { 'tag:' ~ key: value } }}"
      register: ec2_metadata

    #Output the metadata of the EC2 instances
    - debug: msg="{{ ec2_metadata.instances }}"

    #Output the Instance Id of the first EC2 instance returned in the metadata
    - debug: msg="{{ ec2_metadata.instances[0].instance_id }}"

    #Terminating the EC2 instances and waiting for them to reach the desired state
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: "{{ region }}"
        instance_ids: '{{ item.instance_id }}'
        wait: True
      loop : "{{ ec2_metadata.instances }}"
