---
### Playbook to terminate all instances with a given tag

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: True
  vars:
    keypair: test-keypair
    instance_type: t2.micro
    security_group: sg-06bded1a985de0760
    image: ami-9887c6e7
    region: us-east-1
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts :
        filters:
          "tag:type": test_instance
      register: instance

    # - debug: msg="{{ item.instance_id }}"
    #   loop : "{{ instance.instances }}"

    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: "{{ region }}"
        instance_ids: '{{ item.instance_id }}'
        wait: True
      loop : "{{ instance.instances }}"
