# Ansible Playbook to terminate the EC2 instances tagged with the KEY, VALUE and REGION passed as Command line arguements
- hosts: localhost
  vars:
   region: "{{ region }}" #Passed as CLI argument
   key: "{{ key }}" #Passed as CLI argument
   value: "{{ value }}" #Passed as CLI argument 
  tasks:
   # Gather facts about any instance with the tag(Key, Value) passed
   - ec2_instance_facts:
      filters:
       "{{ { 'tag:' ~ key: value } }}"
     register: ec2_metadata
   #Output the metadata of the EC2 instances
   - debug: msg="{{ ec2_metadata.instances }}"
   #Output the Instance Id of the first EC2 instance returned in the metadata
   - debug: msg="{{ ec2_metadata.instances[0].instance_id }}"
   #Terminating the EC2 instances and waiting for them to reach the desired state
   - name: Terminate all EC2 instances with the Key and Value passed
     ec2:
      instance_ids: '{{ item.instance_id }}'
      region: '{{ region }}'
      state: absent
      wait: True
     with_items: "{{ ec2_metadata.instances }}"
