---
- name: ec2 launcher
  hosts: localhost
  vars:
    region: "{{ region }}" # Passed as cli argument
    ssh_key: "{{ ssh_key }}" # Passed as cli argument
    ssh_pem_file_location: "{{ssh_pem_file_location}}"
  connection: local
  tasks:
  - name: Check for default vpc
    ec2_vpc_net_facts:
      region: '{{region}}'
    register: ec2_vpc_net_facts_results

  - name: check running instances

  # Gather facts about any instance with a tag key 'app' and value 'web'
    ec2_instance_facts:
      filters:
        instance-state-name: ["running"]
        "tag:app": web
    register: ec2_metadata
    
  #Output the Instance Id of the first EC2 instance returned in the metadata
  #- debug: msg="{{ ec2_metadata.instances[0].instance_id }}"
  
  #Create Security Group for EC2_instance
  - name: "Create a new security group"
    ec2_group:
      name: "ansible-sec-group"
      description: "New SG for Ansible-created instances"
      region: "{{ region }}"
      vpc_id: "{{default_vpc.id}}"
      rules:
        - proto: "tcp"
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
        - proto: "tcp"
          from_port: 80
          to_port: 80
          cidr_ip: "0.0.0.0/0"
      rules_egress:
        - proto: "all"
          cidr_ip: "0.0.0.0/0"
      tags:
        app: web
    vars:
      default_vpc: '{{(ec2_vpc_net_facts_results|json_query("vpcs[?is_default]"))[0]}}'
    register: secgrp

  - name: Provision an ec2 instance
    ec2_instance:
      name: "fa-19 ansible instance"
      key_name: "{{ ssh_key }}"
      instance_type: t2.micro
      security_group: "{{ secgrp.group_id }}"
      region: "{{ region }}"
      network:
        assign_public_ip: true
      image_id: ami-9887c6e7
      volumes:
        - device_name: /dev/sda1
          ebs:
            volume_size: 8
            delete_on_termination: true
      wait: true
      tags:
        app: web
    register: ec2instance

  - debug: msg="{{ ec2instance.instances[0] }}"

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip_address}}"
      groupname: launched
    loop: "{{ ec2instance.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip_address }}"
      port: 22 
      state: started 
    with_items: "{{ ec2instance.instances }}"

- name: Configure instance
  hosts: launched
  become: yes
  remote_user: centos
  vars:
    ansible_ssh_private_key_file: "{{ssh_pem_file_location}}"
  tasks:
    - name: create symbolic link to call python2 ahead of python3
      raw: sudo ln -sf python2 /usr/bin/python

    - name: update yum package
      command: yum update -y

    - name: install the latest version of Apache from the testing repo
      yum:
        name: httpd
        state: latest

    - name: ensure apache is running
      service:
        name: httpd
        state: started

    - name: write the apache config file
      template:
        src: srv/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify:
      - restart apache
    
    - name: install the latest version of python3
      yum:
        name: python3
        state: present

    - name: create symbolic link to call python3 ahead of python2
      raw: sudo ln -sf python3 /usr/bin/python

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted